### ISSUE TITLE
GLIBC compatibility

### ISSUE THREAD

**Issue by trongnd32** [domferr/Linux-PowerToys#2]
Hello. I am a fan of PowerToys in Windows. Currently, my job requires transitioning to Ubuntu and I am finding PowerToys alternative in Ubuntu. I found your project and it's amazing. Unluckily, I can't install your release in my machine, because it requires GLIBC_2.34, which can't run on Ubuntu 20.04. 

Could you please downgrade dependencies to make this project available for older Ubuntu version?
Thank you!

**Comment by domferr** [comment]
Hey thank you! 
Since it is under development, I didn't test on Ubuntu 20.04 yet, so I'm more than happy to look into this issue. Do you have any logs to share?

**Comment by domferr** [comment]
Meanwhile I created a new build that should support glibc versions even lower than 2.34.
Can you confirm that it runs on your Ubuntu 20.04? If that's the case, please let me know if the utilities are working too :smile: 

[LinuxPowerToys-latest-x86_64.zip](https://github.com/domferr/Linux-PowerToys/files/15468886/LinuxPowerToys-latest-x86_64.zip)

**Comment by trongnd32** [comment]
Thank you. I will try the new build tomorrow, when I go to the office. I'm at home now and I don't have Ubuntu machine

**Comment by trongnd32** [comment]
Today I tried your new build. After install some dependencies, I can launch the app. But FancyZones seem not work. When I click on add layout button, nothing happened. This is log when I click on it:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.Extensions.ModernWindowManager” on object at path /org/gnome/shell/extensions/ModernWindowManager
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1126)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:621)
<asynchronous suspension>
#2      GnomeFancyZonesBackend._openLayoutEditor (package:linuxpowertoys/src/backend_api/utilities/fancy_zones/gnome_fancy_zones_backend.dart:320)
<asynchronous suspension>
```

**Comment by domferr** [comment]
> Today I tried your new build. After install some dependencies, I can launch the app

Oh that's great! We solved the problem about glibc compatibility.

> But FancyZones seem not work

Are you using GNOME Shell? If yes, which version?

**Comment by trongnd32** [comment]
> Are you using GNOME Shell? If yes, which version?

Sorry because of late response. I use GNOME shell version 3.38 at first, then I updated to version 41. In both versions, FancyZones didn't work.

**Comment by domferr** [comment]
Unfortunately, the tool implementing FancyZones supports GNOME versions from 42 :disappointed:
